# name: Run Smoke Tests postman

# on:
#   workflow_dispatch:
#     inputs:
#       tags:
#         description: "Tests cenario postman"
#         required: true
#         default: "smoke"

# jobs:
#   run_smoke_tests:
#     runs-on: ubuntu-20.04

#     # defaults:
#     #   run:
#     #     shell: bash
#     #     working-directory: ./tests

#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a set of commands using the runners shell
#       - name: Step 1 Check version Newman and Node
#         run: |
#           newman --version
#           node --version

#       - name: Step 2 Install Newman-Reporter-Htmlextra
#         run: sudo npm install -g newman-reporter-htmlextra

#       - name: Step 3 npm install -g newman-reporter-allure
#         run: sudo npm install -g newman-reporter-allure
        
#       # - name: Prepare Allure history
#       #   run: |
#       #     cd ..
#       #     mkdir -p allure-results

#       - name: Step 3 Execute collection
#         run: newman run ./test.json -e ./qa.json -r allure --reporter-allure-export allure-report

#       - name: Get Allure history
#         uses: actions/checkout@v2
#         if: always()
#         continue-on-error: true
        
#       - name: Step 3 Execute collection
#         run: newman run ./test.json -e ./qa.json -r allure --reporter-allure-export allure-report

#         with:
#           ref: gh-pages
#           path: gh-pages

#       - name: Allure Report action from marketplace
#         uses: simple-elf/allure-report-action@master
#         if: always()
#         id: allure-report
#         with:
#           allure_results: allure-results
#           gh_pages: gh-pages
#           allure_report: allure-report
#           allure_history: allure-history

#       - name: Deploy report to Github Pages
#         if: always()
#         uses: peaceiris/actions-gh-pages@v2
#         env:
#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PUBLISH_BRANCH: gh-pages
#           PUBLISH_DIR: allure-history


########################################################################################################################
name: Pipeline de testes com allure-report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-checking:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    #     distribution: 'adopt'
        
    # - name: Step 1 Check version Newman and Node
    #   run: |
    #     newman --version
    #     node --version

    # - name: Step 2 Install Newman-Reporter-Htmlextra
    #   run: sudo npm install -g newman-reporter-htmlextra
    # - name: Step 3 npm install -g newman-reporter-allure
    #   run: sudo npm install -g newman-reporter-allure        
    # - name: Step 3 Execute collection
    #   run: newman run ./test.json -e ./qa.json -r allure --reporter-allure-export allure-report

  # Tests:
  #   runs-on: ubuntu-latest

    # steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 npm install -g newman-reporter-allure
        run: sudo npm install -g newman-reporter-allure
        

      - name: Step 3 Execute collection
        run: newman run ./test.json -e ./qa.json -r allure --reporter-allure-export allure-report


      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history